version: "3"

services:
  apps: 
    build: 
      context: .
      dockerfile: Dockerfile
    image: shortly
    depends_on:
      - db
    container_name: shortly
    ports: 
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      SERVER_PORT: ${SERVER_PORT}
      BASE_URL: ${BASE_URL}

